### ISSUE TITLE
Improve Editor UI

### ISSUE THREAD

**Issue by lakshya-roonwal** [lakshya-roonwal/resume-creator#1]
### Improve the Editor UI so it could look better and be responsive
![image](https://github.com/user-attachments/assets/8bb54bd4-88f5-47f5-a935-3a7dd8e4e79e)

**Comment by ankur-kalita** [comment]
hey,  @lakshya-roonwal  I want to work on this issue,  Could you please assign it to me?

**Comment by lakshya-roonwal** [comment]
Sure...pull the latest changes in your fork and you can start working on it.
