### ISSUE TITLE
Fix Select in Edit Skills Section

### ISSUE THREAD

**Issue by lakshya-roonwal** [lakshya-roonwal/resume-creator#2]
The Exact category of skills need to be selected and show and by default there should be a placehoder or some default category
![image](https://github.com/user-attachments/assets/e50228ae-2488-4366-83e6-b6f0bc22de37)

**Comment by DavidReque** [comment]
can I work on this?

**Comment by lakshya-roonwal** [comment]
Sure ...Assigned to you

**Comment by ankur-kalita** [comment]
Hi @lakshya-roonwal ,

I want to work on this issue. Could you please assign it to me?

Thanks!

**Comment by ankur-kalita** [comment]
hey @lakshya-roonwal I'd like to work on this issue. Could you please assign it to me?

**Comment by lakshya-roonwal** [comment]
> hey @lakshya-roonwal I'd like to work on this issue. Could you please assign it to me?

It is fixed and issue will be closed you can work on other issues
