### ISSUE TITLE
Create a floating tool bar in Resume Section

### ISSUE THREAD

**Issue by lakshya-roonwal** [lakshya-roonwal/resume-creator#5]
### Bottom Tool bar

In the resume section a floating toolbar can be there which will have some buttons like zoom-in , zoom-out , center and can be download button as well 
![image](https://github.com/user-attachments/assets/59b72779-abb7-43db-b4ce-e613fe0760a7)

**Comment by MrRohit-01** [comment]
i'm working on this issue.

**Comment by MrRohit-01** [comment]
@lakshya-roonwal can you assign it to me??

**Comment by lakshya-roonwal** [comment]
Sure ....you can checkout the **PDFDownloadLink** in the ```Editor.tsx``` file you will get the idea of functionality

**Comment by MrRohit-01** [comment]
@lakshya-roonwal added the Zoom in, Zoom out, reset button on buttom of resume, checkout the video
Edited:- moved that tool bar little above
[Screencast from 2024-07-19 18-40-32.webm](https://github.com/user-attachments/assets/c1e171b3-1508-45b9-bd7d-2f3fb68076d8)

**Comment by MrRohit-01** [comment]
@lakshya-roonwal bhaiya, you have changed the download button from BuilderPage.tsx to Editor.tsx, 
then i won't have to add download button on tool bar??

**Comment by MrRohit-01** [comment]
checkout the pr @lakshya-roonwal @DavidReque

**Comment by lakshya-roonwal** [comment]
@Mrdevil-01 will check today ....you are going great btw

**Comment by MrRohit-01** [comment]
thanks
